// Demo config for the fixture calendar — `make demo` mounts this directory as
// /config and starts the display on http://localhost:8081 with no Google
// account, no API key, and no network access required.
//
// The rules below are also a live example of field-level fall-through: the
// Denver rule sets a color and no symbol, so the Flight rule underneath it
// still gets to supply the plane icon.

module.exports = {
  calendars: [
    {
      type: 'fixture',
      name: 'Demo',
      color: '#5B7DB1',
      path: '/config/demo.ics', // generated by tools/generate-demo-ics.js
    },
  ],

  customEvents: [
    { keyword: 'Denver', color: '#7C6BB1' },              // color only…
    { keyword: 'Flight', symbol: 'fa-solid fa-plane' },   // …symbol falls through to here
    { keyword: 'Standup', hide: true },                   // drop the daily standup
    {
      keyword: 'Birthday',
      color: 'Gold',
      symbol: 'fa-solid fa-cake-candles',
      transform: { search: "^(.*) '(\\d{4})$", replace: '$1 ($2)', yearmatchgroup: 2 },
    },
    { keyword: 'Soccer',   color: '#C97064', symbol: 'fa-solid fa-futbol' },
    { keyword: 'Dentist|Vet|cleaning', color: '#5FA8A0', symbol: 'fa-solid fa-stethoscope' },
    { keyword: 'Trash',    symbol: 'fa-solid fa-trash' },
    { keyword: 'market|Grocery', color: '#6AA84F', symbol: 'fa-solid fa-basket-shopping' },
    { keyword: 'Piano|Book club|Trivia|Board game', symbol: 'fa-solid fa-music' },
    { keyword: 'trip|Hotel', color: '#B18F5B', symbol: 'fa-solid fa-suitcase' },
  ],

  settings: {
    weekStartsOn: 0,
    use24HourClock: false,
    agendaDaysAhead: 60,
    refreshMinutes: 5,
    maxEventsPerDayCell: 0, // as many as fit
    weekStripHeight: '120px',
    port: 3000,
    configPassword: '',
    theme: {
      ink:       '#12181B',
      panel:     '#1B2327',
      panelLine: '#2A3439',
      text:      '#EDEAE2',
      textDim:   '#8C979B',
      todayRing: '#5FA8A0',
    },
  },

  googleTasks: { enabled: false },
};
